package remediate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// Runner is the test seam for opening a pull request. The real implementation
// (GitCLI) shells out to git and gh; tests use a fake that records calls. All
// side effects of OpenPR go through this interface so the orchestration is
// unit-tested without a live remote.
type Runner interface {
	// Dirty reports whether any of files has uncommitted changes.
	Dirty(files []string) (bool, error)
	// BaseBranch returns the current branch, used as the PR base.
	BaseBranch() (string, error)
	CreateBranch(name string) error
	Add(files []string) error
	Commit(message string) error
	Push(branch string) error
	// CreatePR opens the PR and returns its URL.
	CreatePR(title, body, base string) (string, error)
}

// PROptions tunes OpenPR.
type PROptions struct {
	Branch string // optional branch name; empty -> generated
	// now is injected for deterministic branch names in tests; nil -> time.Now.
	now func() time.Time
}

// OpenPR applies the patches onto a new branch and opens a pull request whose
// body explains each change. It checks the working tree is clean for the target
// files *before* writing (so the dirty guard catches pre-existing unrelated
// edits, not our own), then branches, writes, commits, pushes and PRs. root is
// the scan root that Patch.File paths are relative to.
func OpenPR(root string, patches []Patch, opts PROptions, r Runner) (string, error) {
	if len(patches) == 0 {
		return "", fmt.Errorf("no patches to open a PR for")
	}

	files := patchFiles(patches)

	dirty, err := r.Dirty(files)
	if err != nil {
		return "", fmt.Errorf("check working tree: %w", err)
	}
	if dirty {
		return "", fmt.Errorf("uncommitted changes in %s; stash or commit them before --open-pr", strings.Join(files, ", "))
	}

	base, err := r.BaseBranch()
	if err != nil {
		return "", fmt.Errorf("resolve base branch: %w", err)
	}

	branch := opts.Branch
	if branch == "" {
		branch = generatedBranch(patches, opts.now)
	}

	if err := r.CreateBranch(branch); err != nil {
		return "", fmt.Errorf("create branch %s: %w", branch, err)
	}
	for _, p := range patches {
		if err := os.WriteFile(filepath.Join(root, p.File), []byte(p.NewContent), 0o644); err != nil {
			return "", fmt.Errorf("apply %s: %w", p.File, err)
		}
	}
	if err := r.Add(files); err != nil {
		return "", fmt.Errorf("stage files: %w", err)
	}
	if err := r.Commit(commitMessage()); err != nil {
		return "", fmt.Errorf("commit: %w", err)
	}
	if err := r.Push(branch); err != nil {
		return "", fmt.Errorf("push %s: %w", branch, err)
	}
	url, err := r.CreatePR(prTitle(), prBody(patches), base)
	if err != nil {
		return "", fmt.Errorf("open PR: %w", err)
	}
	return url, nil
}

// patchFiles returns the sorted, de-duplicated file list across patches.
func patchFiles(patches []Patch) []string {
	seen := map[string]bool{}
	var files []string
	for _, p := range patches {
		if !seen[p.File] {
			seen[p.File] = true
			files = append(files, p.File)
		}
	}
	sort.Strings(files)
	return files
}

// generatedBranch builds a stable-shaped branch name from the rules applied.
func generatedBranch(patches []Patch, now func() time.Time) string {
	if now == nil {
		now = time.Now
	}
	rules := map[string]bool{}
	var ordered []string
	for _, p := range patches {
		for r := range strings.SplitSeq(p.Rule, ",") {
			r = kebab(r)
			if r != "" && !rules[r] {
				rules[r] = true
				ordered = append(ordered, r)
			}
		}
	}
	sort.Strings(ordered)
	stamp := now().UTC().Format("20060102150405")
	return "qryx/fix-" + strings.Join(ordered, "-") + "-" + stamp
}

func commitMessage() string {
	return "fix: raise weak crypto key sizes (qryx)"
}

func prTitle() string {
	return "fix: remediate weak cryptography (qryx)"
}

// prBody renders the PR description: one section per file with rules, rationale
// and the unified diff.
func prBody(patches []Patch) string {
	var b strings.Builder
	b.WriteString("Automated cryptography remediation generated by `qryx fix`.\n\n")
	b.WriteString("Each change is a provably safe transform (only key-size literals are ")
	b.WriteString("raised); algorithm migrations are left to human review.\n\n")
	for _, p := range patches {
		fmt.Fprintf(&b, "### `%s` (%s)\n\n", p.File, p.Rule)
		if p.Rationale != "" {
			fmt.Fprintf(&b, "%s\n\n", p.Rationale)
		}
		b.WriteString("```diff\n")
		b.WriteString(p.Diff)
		if !strings.HasSuffix(p.Diff, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("```\n\n")
	}
	b.WriteString("---\nGenerated by qryx.\n")
	return b.String()
}

// kebab lowercases and replaces runs of non-alphanumeric characters with single
// hyphens, trimming leading/trailing hyphens.
func kebab(s string) string {
	var b strings.Builder
	prevHyphen := false
	for _, r := range strings.ToLower(s) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			prevHyphen = false
		default:
			if !prevHyphen {
				b.WriteByte('-')
				prevHyphen = true
			}
		}
	}
	return strings.Trim(b.String(), "-")
}
